export const colors = ['red','yellow','green','blue'] as const;
export type Color = typeof colors[number];
export type Value = number | 'skip' | 'reverse' | 'draw2' | 'wild' | 'draw4';
export interface Card {id:string;color:Color|'wild';value:Value}
export interface Player {id:string;name:string;avatar:string;bot:boolean;hand:Card[];uno:boolean;connected:boolean}
export interface Settings {startingCards:number;timer:number;stacking:boolean;drawUntilPlayable:boolean;forcePlay:boolean;difficulty:'easy'|'medium'|'hard';mode:'classic'|'quick'|'teams'|'tournament'|'chaos';target:number}
export const defaults:Settings={startingCards:7,timer:30,stacking:false,drawUntilPlayable:false,forcePlay:false,difficulty:'medium',mode:'classic',target:0};
export interface Game {id:string;players:Player[];deck:Card[];discard:Card[];color:Color;turn:number;direction:1|-1;pendingDraw:number;drawn:string|null;status:'playing'|'finished';winner:string|null;score:number;settings:Settings;deadline:number;revision:number;log:string[];unoUntil:number;unoPlayer:string|null;startedAt:number}
export function makeDeck():Card[]{let n=0;const result:Card[]=[];for(const color of colors){result.push({id:String(n++),color,value:0});for(let copy=0;copy<2;copy++)for(const value of [1,2,3,4,5,6,7,8,9,'skip','reverse','draw2'] as Value[])result.push({id:String(n++),color,value});}for(let i=0;i<4;i++)for(const value of ['wild','draw4'] as Value[])result.push({id:String(n++),color:'wild',value});return result;}
export function shuffle<T>(items:T[],random= Math.random):T[]{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function createGame(id:string,people:Omit<Player,'hand'|'uno'>[],settings:Partial<Settings>={},random=Math.random,now=Date.now()):Game {if(people.length<2||people.length>4)throw Error('A game needs 2–4 players.');const opts={...defaults,...settings};const deck=shuffle(makeDeck(),random);const players=people.map(p=>({...p,hand:deck.splice(0,opts.startingCards),uno:false}));const start=deck.findIndex(c=>typeof c.value==='number');const top=deck.splice(start,1)[0];return {id,players,deck,discard:[top],color:top.color as Color,turn:0,direction:1,pendingDraw:0,drawn:null,status:'playing',winner:null,score:0,settings:opts,deadline:opts.timer?now+opts.timer*1000:0,revision:0,log:['A fresh deck. A new rivalry. Let’s play!'],unoUntil:0,unoPlayer:null,startedAt:now};}
export function legal(g:Game,p:Player,c:Card){if(g.pendingDraw)return g.settings.stacking && c.value===(g.discard.at(-1)!.value) && (c.value==='draw2'||(c.value==='draw4'&&!p.hand.some(x=>x.color===g.color)));if(c.value==='draw4')return !p.hand.some(x=>x.color===g.color);return c.color==='wild'||c.color===g.color||c.value===g.discard.at(-1)!.value;}
export function score(hand:Card[]){return hand.reduce((s,c)=>s+(typeof c.value==='number'?c.value:c.color==='wild'?50:20),0);}
function take(g:Game,p:Player,count:number){for(let i=0;i<count;i++){if(!g.deck.length){if(g.discard.length<=1)break;const top=g.discard.pop()!;let seed=((g.revision+1)*2654435761+i)>>>0;g.deck=shuffle(g.discard,()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;});g.discard=[top];}const c=g.deck.pop();if(c)p.hand.push(c);}p.uno=false;}
function advance(g:Game,steps=1,now=Date.now()){g.turn=(g.turn+g.direction*steps+g.players.length*2)%g.players.length;g.drawn=null;g.deadline=g.settings.timer?now+g.settings.timer*1000:0;}
export type Action={type:'play';cardId:string;color?:Color}|{type:'draw'}|{type:'pass'}|{type:'uno'}|{type:'catch'};
export function act(g:Game,id:string,action:Action,now=Date.now()){if(g.status!=='playing')throw Error('This round has finished.');const p=g.players.find(x=>x.id===id);if(!p)throw Error('You are not in this game.');
if(action.type==='uno'){if(p.hand.length!==1&&!(p.hand.length===2&&g.players[g.turn].id===id))throw Error('Call UNO when you are down to your last card.');p.uno=true;if(g.unoPlayer===id){g.unoUntil=0;g.unoPlayer=null;}g.log.push(`${p.name} calls UNO!`);g.revision++;return;}
if(action.type==='catch'){if(!g.unoPlayer||g.unoPlayer===id||now>g.unoUntil)throw Error('There is nobody to catch.');const other=g.players.find(x=>x.id===g.unoPlayer)!;if(other.uno)throw Error('They already called UNO.');take(g,other,2);g.log.push(`${p.name} caught ${other.name}! +2 cards.`);g.unoPlayer=null;g.unoUntil=0;g.revision++;return;}
if(g.players[g.turn].id!==id)throw Error('Wait for your turn.');
if(action.type==='play'){const card=p.hand.find(c=>c.id===action.cardId);if(!card)throw Error('That card is not in your hand.');if(!legal(g,p,card)||(g.drawn&&card.id!==g.drawn))throw Error('Match the active color or symbol.');if(card.color==='wild'&&!colors.includes(action.color!))throw Error('Choose the next color.');p.hand=p.hand.filter(c=>c.id!==card.id);g.discard.push(card);g.color=card.color==='wild'?action.color!:card.color;g.drawn=null;g.log.push(`${p.name} played ${card.color==='wild'?'wild':card.color} ${card.value}.`);let steps=1;if(card.value==='reverse'){g.direction=g.direction===1?-1:1;if(g.players.length===2)steps=2;}if(card.value==='skip')steps=2;if(card.value==='draw2'||card.value==='draw4'){g.pendingDraw+=card.value==='draw2'?2:4;if(!g.settings.stacking){const next=(g.turn+g.direction+g.players.length)%g.players.length;take(g,g.players[next],g.pendingDraw);g.pendingDraw=0;steps=2;}}
if(p.hand.length===1&&!p.uno){g.unoPlayer=id;g.unoUntil=now+4000;}else if(p.hand.length!==1)p.uno=false;
if(!p.hand.length){if(g.pendingDraw){take(g,g.players[(g.turn+g.direction+g.players.length)%g.players.length],g.pendingDraw);g.pendingDraw=0;}g.status='finished';g.winner=id;g.score=g.players.filter(x=>x.id!==id).reduce((s,x)=>s+score(x.hand),0);g.log.push(`${p.name} wins the round with ${g.score} points!`);}else advance(g,steps,now);
}else if(action.type==='draw'){if(g.drawn)throw Error('Play your drawn card or pass.');if(g.pendingDraw){take(g,p,g.pendingDraw);g.log.push(`${p.name} draws ${g.pendingDraw}.`);g.pendingDraw=0;advance(g,1,now);}else{let count=0;do{const old=p.hand.length;take(g,p,1);count++;if(old===p.hand.length)break;}while(g.settings.drawUntilPlayable&&!legal(g,p,p.hand.at(-1)!)&&count<108);const card=p.hand.at(-1)!;g.log.push(`${p.name} draws ${count} card${count>1?'s':''}.`);if(legal(g,p,card)){g.drawn=card.id;if(g.settings.forcePlay)act(g,id,{type:'play',cardId:card.id,color:bestColor(p.hand)},now);}else advance(g,1,now);}}else {if(!g.drawn)throw Error('Draw a card before passing.');advance(g,1,now);}g.revision++;g.log=g.log.slice(-30);}
export function bestColor(hand:Card[]):Color{return [...colors].sort((a,b)=>hand.filter(c=>c.color===b).length-hand.filter(c=>c.color===a).length)[0];}
export function botAction(g:Game):Action{const p=g.players[g.turn];const options=p.hand.filter(c=>legal(g,p,c)&&(!g.drawn||c.id===g.drawn));if(!options.length)return {type:g.drawn?'pass':'draw'};const next=g.players[(g.turn+g.direction+g.players.length)%g.players.length];const chosen=options.sort((a,b)=>{const weight=(c:Card)=> (c.color===bestColor(p.hand)?5:0)+(typeof c.value==='number'?c.value/3:next.hand.length<3?20:7)-(c.color==='wild'&&p.hand.length>3?12:0);return g.settings.difficulty==='easy'?0:weight(b)-weight(a);})[0];return {type:'play',cardId:chosen.id,color:bestColor(p.hand.filter(c=>c.id!==chosen.id))};}
export function view(g:Game,id:string){return {...g,deck:undefined,deckCount:g.deck.length,discard:g.discard.slice(-1),players:g.players.map(p=>({...p,hand:p.id===id?p.hand:undefined,cardCount:p.hand.length})),legalCards:g.players[g.turn].id===id?g.players[g.turn].hand.filter(c=>legal(g,g.players[g.turn],c)&&(!g.drawn||g.drawn===c.id)).map(c=>c.id):[]};}
