import {Pool} from 'pg';
import {randomBytes,randomUUID,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import type {Express,Request} from 'express';
import {z} from 'zod';
export const db=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL}):null;
export const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
const passwordHash=(v:string)=>{const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(v,salt,64).toString('hex');};
const passwordMatches=(v:string,h:string)=>{const [salt,key]=h.split(':');return timingSafeEqual(scryptSync(v,salt,64),Buffer.from(key,'hex'));};
export function cookie(req:Request|{headers:{cookie?:string}}){return req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('session='))?.slice(8);}
export async function userFor(token?:string){if(!db||!token)return null;const {rows}=await db.query('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now() AND NOT u.banned',[hash(token)]);return rows[0]||null;}
const publicUser=(u:any)=>{if(!u)return null;const {password_hash,email,...safe}=u;return safe;};
export function setupDatabaseRoutes(app:Express){
app.get('/api/me',async(req,res)=>{try{res.json({user:publicUser(await userFor(cookie(req))),database:!!db});}catch{res.status(503).json({error:'Account services are unavailable.'});}});
app.post('/api/auth/:action',async(req,res)=>{try{if(!db){res.status(503).json({error:'Accounts need a PostgreSQL connection. You can still play as a guest.'});return;}const action=req.params.action;
if(action==='logout'){await db.query('DELETE FROM sessions WHERE token_hash=$1',[hash(cookie(req)||'')]);res.clearCookie('session').json({ok:true});return;}
if(action==='forgot'){const email=z.string().email().parse(req.body.email);const {rows}=await db.query('SELECT id FROM users WHERE email=$1',[email.toLowerCase()]);if(rows[0]&&process.env.MAIL_WEBHOOK_URL){const token=randomBytes(32).toString('hex');await db.query('INSERT INTO password_resets VALUES($1,$2,now()+interval \'30 minutes\')',[hash(token),rows[0].id]);await fetch(process.env.MAIL_WEBHOOK_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to:email,resetUrl:`${process.env.APP_URL}/login?reset=${token}`})});}res.json({ok:true,message:'If the account exists, a reset link will be sent when email delivery is configured.'});return;}
if(action==='reset'){const {token,password}=z.object({token:z.string().min(32),password:z.string().min(10).max(128)}).parse(req.body);const client=await db.connect();try{await client.query('BEGIN');const {rows}=await client.query('DELETE FROM password_resets WHERE token_hash=$1 AND expires_at>now() RETURNING user_id',[hash(token)]);if(!rows[0])throw Error('Reset link is invalid or expired.');await client.query('UPDATE users SET password_hash=$1 WHERE id=$2',[passwordHash(password),rows[0].user_id]);await client.query('DELETE FROM sessions WHERE user_id=$1',[rows[0].user_id]);await client.query('COMMIT');res.json({ok:true});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}return;}
const data=z.object({email:z.string().email().max(254),password:z.string().min(10).max(128),username:z.string().min(2).max(24).regex(/^[a-zA-Z0-9_ ]+$/).optional()}).parse(req.body);let user;
if(action==='register'){if(!data.username)throw Error('Choose a username.');const r=await db.query('INSERT INTO users(id,email,username,password_hash) VALUES($1,$2,$3,$4) RETURNING *',[randomUUID(),data.email.toLowerCase(),data.username,passwordHash(data.password)]);user=r.rows[0];}else if(action==='login'){const r=await db.query('SELECT * FROM users WHERE email=$1',[data.email.toLowerCase()]);user=r.rows[0];if(!user||!passwordMatches(data.password,user.password_hash)||user.banned){res.status(401).json({error:'Email or password is incorrect.'});return;}}else throw Error('Unknown request.');
const token=randomBytes(32).toString('hex');await db.query('INSERT INTO sessions VALUES($1,$2,now()+interval \'30 days\')',[hash(token),user.id]);res.cookie('session',token,{httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production',maxAge:2592000000}).json({user:publicUser(user)});
}catch(e:any){res.status(400).json({error:e?.code==='23505'?'That email or username is already in use.':e instanceof z.ZodError?'Check your details. Passwords need at least 10 characters.':'Unable to complete this request. Please try again.'});}});
app.get('/api/leaderboard',async(req,res)=>{try{res.json({users:db?(await db.query("SELECT u.username,u.avatar,COUNT(*)::integer AS games_played,COUNT(*) FILTER (WHERE p.result='win')::integer AS wins,SUM(CASE WHEN p.result='win' THEN 100 ELSE 25 END)::integer AS xp FROM users u JOIN participants p ON p.user_id=u.id JOIN games g ON g.id=p.game_id WHERE NOT u.banned AND g.ranked GROUP BY u.id ORDER BY xp DESC LIMIT 50")).rows:[]});}catch{res.status(503).json({error:'Rankings are unavailable.'});}});
app.get('/api/profile/:username',async(req,res)=>{try{const u=db?(await db.query('SELECT * FROM users WHERE username=$1 AND NOT banned',[req.params.username])).rows[0]:null;res.json({user:publicUser(u)});}catch{res.status(503).json({error:'Profile is unavailable.'});}});
app.use('/api/account',async(req,res,next)=>{try{const user=await userFor(cookie(req));if(!user){res.status(401).json({error:'Sign in to use this feature.'});return;}res.locals.user=user;next();}catch{res.status(503).json({error:'Account services are unavailable.'});}});
app.patch('/api/account/profile',async(req,res)=>{try{const d=z.object({username:z.string().min(2).max(24),avatar:z.string().max(16),background:z.enum(['classic','neon','space','arcade'])}).parse(req.body);await db!.query('UPDATE users SET username=$1,avatar=$2,background=$3 WHERE id=$4',[d.username,d.avatar,d.background,res.locals.user.id]);res.json({ok:true});}catch{res.status(400).json({error:'Could not save profile. Try another username.'});}});
app.get('/api/account/history',async(req,res)=>{try{res.json({games:(await db!.query('SELECT g.*,p.result,p.score FROM participants p JOIN games g ON g.id=p.game_id WHERE p.user_id=$1 ORDER BY g.finished_at DESC LIMIT 50',[res.locals.user.id])).rows});}catch{res.status(503).json({error:'History is unavailable.'});}});
app.get('/api/account/achievements',async(req,res)=>{try{res.json({achievements:(await db!.query('SELECT a.*,ua.unlocked_at FROM achievements a LEFT JOIN user_achievements ua ON ua.achievement_id=a.id AND ua.user_id=$1',[res.locals.user.id])).rows});}catch{res.status(503).json({error:'Achievements are unavailable.'});}});
app.get('/api/account/friends',async(req,res)=>{try{res.json({friends:(await db!.query('SELECT f.*,u.username,u.avatar,u.id FROM friendships f JOIN users u ON u.id=CASE WHEN f.requester_id=$1 THEN f.receiver_id ELSE f.requester_id END WHERE f.requester_id=$1 OR f.receiver_id=$1',[res.locals.user.id])).rows});}catch{res.status(503).json({error:'Friends are unavailable.'});}});
app.post('/api/account/friends',async(req,res)=>{try{const d=z.object({username:z.string().min(2).max(24)}).parse(req.body);const u=(await db!.query('SELECT id FROM users WHERE username=$1',[d.username])).rows[0];if(!u||u.id===res.locals.user.id)throw Error();await db!.query('INSERT INTO friendships(requester_id,receiver_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[res.locals.user.id,u.id]);res.json({ok:true});}catch{res.status(400).json({error:'Could not send request. Check the username.'});}});
app.patch('/api/account/friends',async(req,res)=>{try{const d=z.object({id:z.string().uuid(),accept:z.boolean()}).parse(req.body);if(d.accept)await db!.query('UPDATE friendships SET status=\'accepted\' WHERE requester_id=$1 AND receiver_id=$2',[d.id,res.locals.user.id]);else await db!.query('DELETE FROM friendships WHERE (requester_id=$1 AND receiver_id=$2) OR (requester_id=$2 AND receiver_id=$1)',[d.id,res.locals.user.id]);res.json({ok:true});}catch{res.status(400).json({error:'Could not update friendship.'});}});
}
