import express from 'express';
import {createServer} from 'node:http';
import {randomUUID,randomBytes} from 'node:crypto';
import {Server} from 'socket.io';
import {z} from 'zod';
import {createGame,act,botAction,view,defaults,type Game,type Settings,type Player} from '../src/game/engine';
import {setupDatabaseRoutes,userFor,cookie,db,ensureSchema} from './database';
const app=express();const http=createServer(app);const io=new Server(http,{maxHttpBufferSize:65536});app.disable('x-powered-by');app.use(express.json({limit:'16kb'}));
await ensureSchema().catch(error=>console.error('Database initialization failed; guest play remains available.',error));
const limits=new Map<string,{count:number;until:number}>();app.use('/api',(req,res,next)=>{const origin=req.get('origin');if(origin&&new URL(origin).host!==req.get('host')){res.status(403).json({error:'Request origin is not allowed.'});return;}const key=req.ip||'unknown',now=Date.now();let item=limits.get(key);if(!item||item.until<now){item={count:0,until:now+60000};limits.set(key,item);}if(++item.count>100){res.status(429).json({error:'Too many requests. Please wait a moment.'});return;}next();});setupDatabaseRoutes(app);
type Member=Omit<Player,'hand'|'uno'>&{ready:boolean};
type Room={code:string;host:string;members:Member[];settings:Settings;public:boolean;game:Game|null;chat:{id:string;name:string;text:string}[];saved:boolean;lastActive:number};
const rooms=new Map<string,Room>();const identities=new Map<string,{id:string;name:string;avatar:string}>();
function roomFor(id:string){return [...rooms.values()].find(r=>r.members.some(m=>m.id===id));}
function emitRoom(r:Room){r.lastActive=Date.now();for(const s of io.sockets.sockets.values()){if(s.data.room===r.code)s.emit('state',{code:r.code,host:r.host,members:r.members,settings:r.settings,public:r.public,chat:r.chat,game:r.game?view(r.game,s.data.identity.id):null});}}
const settingsSchema=z.object({startingCards:z.number().int().min(3).max(12),timer:z.union([z.literal(0),z.literal(15),z.literal(30),z.literal(45),z.literal(60)]),stacking:z.boolean(),drawUntilPlayable:z.boolean(),forcePlay:z.boolean(),difficulty:z.enum(['easy','medium','hard']),mode:z.enum(['classic','quick','chaos']),target:z.literal(0)}).partial();
const actionSchema=z.discriminatedUnion('type',[z.object({type:z.literal('play'),cardId:z.string().max(8),color:z.enum(['red','yellow','green','blue']).optional()}),...(['draw','pass','uno','catch'] as const).map(type=>z.object({type:z.literal(type)}))]);
io.use(async(socket,next)=>{try{const origin=socket.handshake.headers.origin;if(origin&&new URL(origin).host!==socket.handshake.headers.host)return next(Error('Origin not allowed.'));const user=await userFor(cookie({headers:socket.handshake.headers}));let token=socket.handshake.auth.token;let identity=user?{id:user.id,name:user.username,avatar:user.avatar}:identities.get(token);if(!identity){identity={id:randomUUID(),name:'Guest '+String(Math.floor(1000+Math.random()*9000)),avatar:'😎'};token=randomBytes(32).toString('hex');identities.set(token,identity);}socket.data.identity=identity;socket.data.token=token;next();}catch{next(Error('Unable to connect. Please try again.'));}});
io.on('connection',socket=>{const me=socket.data.identity;socket.emit('identity',{...me,token:socket.data.token});const existing=roomFor(me.id);if(existing){socket.data.room=existing.code;existing.members.find(m=>m.id===me.id)!.connected=true;if(existing.game)existing.game.players.find(p=>p.id===me.id)!.connected=true;emitRoom(existing);}let rate=0;const reset=setInterval(()=>rate=0,1000);
const callPeers=()=>[...io.sockets.sockets.values()].filter(peer=>peer.id!==socket.id&&peer.data.room===socket.data.room&&peer.data.inCall===true);
socket.on('rtc:join',(reply=()=>{})=>{const r=roomFor(me.id);if(!r||r.code!==socket.data.room){reply({error:'Join a room before starting live talk.'});return;}const peers=callPeers();socket.data.inCall=true;for(const peer of peers)peer.emit('rtc:peer-joined',{id:me.id});reply({peers:[...new Set(peers.map(peer=>peer.data.identity.id))]});});
socket.on('rtc:signal',(raw)=>{try{if(!socket.data.inCall||!socket.data.room)return;const signal=z.object({target:z.string().uuid(),data:z.object({description:z.object({type:z.enum(['offer','answer','pranswer','rollback']),sdp:z.string().max(30000).optional()}).optional(),candidate:z.object({candidate:z.string().max(4000),sdpMid:z.string().nullable().optional(),sdpMLineIndex:z.number().int().nullable().optional(),usernameFragment:z.string().nullable().optional()}).optional()}).refine(value=>value.description||value.candidate)}).parse(raw);for(const peer of callPeers())if(peer.data.identity.id===signal.target)peer.emit('rtc:signal',{from:me.id,data:signal.data});}catch{}});
socket.on('rtc:leave',()=>{socket.data.inCall=false;for(const peer of callPeers())peer.emit('rtc:peer-left',{id:me.id});});
socket.on('command',async(raw,reply=()=>{})=>{try{if(++rate>12)throw Error('Slow down a little.');const d=z.object({type:z.string().max(30)}).passthrough().parse(raw);let r=roomFor(me.id);
if(d.type==='list'){reply({rooms:[...rooms.values()].filter(x=>x.public&&!x.game&&x.members.length<4).map(x=>({code:x.code,host:x.members[0].name,count:x.members.length,mode:x.settings.mode}))});return;}
if(d.type==='create'||d.type==='match'){if(r)throw Error('Leave your current room first.');const botGame=d.bots===true;const settings={...defaults,...settingsSchema.parse(d.settings||{})};if(d.type==='match')r=[...rooms.values()].find(x=>x.public&&!x.game&&x.members.length<4);if(r){r.members.push({...me,bot:false,connected:true,ready:false});}else{let code;do{code=randomBytes(3).toString('hex').toUpperCase();}while(rooms.has(code));r={code,host:me.id,members:[{...me,bot:false,connected:true,ready:true}],settings,public:d.type==='match'||d.public===true,game:null,chat:[],saved:false,lastActive:Date.now()};rooms.set(code,r);if(botGame){const count=z.number().int().min(1).max(3).parse(d.count??3);for(let i=0;i<count;i++)r.members.push({id:randomUUID(),name:['Luna','Blaze','Oliver'][i],avatar:['🌙','🔥','🥑'][i],bot:true,connected:true,ready:true});r.game=createGame(randomUUID(),r.members,r.settings);}}socket.data.room=r.code;}
else if(d.type==='join'){if(r)throw Error('Leave your current room first.');const code=z.string().max(6).parse(d.code).toUpperCase();r=rooms.get(code);if(!r)throw Error('Room not found. Check the invite code.');if(r.game)throw Error('This game has already started.');if(r.members.length===4)throw Error('This room is full.');r.members.push({...me,bot:false,connected:true,ready:false});socket.data.room=r.code;}
else {if(!r)throw Error('Join a room first.');if(d.type==='leave'){if(r.game&&r.game.status==='playing'){const p=r.game.players.find(p=>p.id===me.id)!;p.bot=true;p.connected=false;}r.members=r.members.filter(m=>m.id!==me.id);if(r.host===me.id)r.host=r.members.find(m=>!m.bot)?.id||'';socket.data.room=null;socket.emit('state',null);if(!r.members.some(m=>!m.bot))rooms.delete(r.code);else emitRoom(r);reply({ok:true});return;}
if(d.type==='ready'){if(r.game)throw Error('Game already started.');r.members.find(m=>m.id===me.id)!.ready=d.ready===true;}
else if(d.type==='settings'||d.type==='bot'||d.type==='start'||d.type==='rematch'||d.type==='close'){if(r.host!==me.id)throw Error('Only the host can do that.');if(d.type==='close'){for(const s of io.sockets.sockets.values())if(s.data.room===r.code){s.data.room=null;s.emit('state',null);}rooms.delete(r.code);reply({ok:true});return;}if(r.game?.status==='playing')throw Error('Finish the current game first.');if(d.type==='settings')r.settings={...r.settings,...settingsSchema.parse(d.settings)};if(d.type==='bot'){if(d.remove){r.members=r.members.filter(m=>m.id!==d.remove||!m.bot);}else{if(r.members.length>=4)throw Error('Room is full.');r.members.push({id:randomUUID(),name:['Luna','Blaze','Oliver'][r.members.length-1],avatar:['🌙','🔥','🥑'][r.members.length-1],bot:true,connected:true,ready:true});}}if(d.type==='start'||d.type==='rematch'){if(r.members.length<2)throw Error('Add a bot or invite a friend.');if(r.members.some(m=>!m.ready))throw Error('Wait until everyone is ready.');r.game=createGame(randomUUID(),r.members,r.settings);r.saved=false;}}
else if(d.type==='action'){if(!r.game)throw Error('The game has not started.');if(d.revision!==r.game.revision)throw Error('The table changed. Please try again.');act(r.game,me.id,actionSchema.parse(d.action));}
else if(d.type==='chat'){const message=z.string().trim().min(1).max(240).parse(d.text);r.chat.push({id:randomUUID(),name:me.name,text:message});r.chat=r.chat.slice(-60);}else throw Error('Unknown action.');}
if(r)emitRoom(r);reply({ok:true});}catch(e){reply({error:e instanceof z.ZodError?'Please check your settings.':e instanceof Error?e.message:'Unable to complete that action.'});}});
socket.on('disconnect',()=>{clearInterval(reset);for(const peer of callPeers())peer.emit('rtc:peer-left',{id:me.id});if([...io.sockets.sockets.values()].some(s=>s.data.identity.id===me.id))return;const r=roomFor(me.id);if(r){r.members.find(m=>m.id===me.id)!.connected=false;if(r.game)r.game.players.find(p=>p.id===me.id)!.connected=false;emitRoom(r);}});
});
async function saveGame(r:Room){if(!db||!r.game)return;const g=r.game;const c=await db.connect();try{await c.query('BEGIN');await c.query('INSERT INTO games(id,mode,started_at,ranked) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[g.id,g.settings.mode,new Date(g.startedAt),!g.players.some(p=>p.bot)]);for(const p of g.players.filter(x=>!x.bot)){const found=await c.query('SELECT id FROM users WHERE id=$1',[p.id]);if(!found.rowCount)continue;const win=p.id===g.winner;const inserted=await c.query('INSERT INTO participants VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING RETURNING user_id',[g.id,p.id,win?'win':'loss',win?g.score:0]);if(!inserted.rowCount)continue;await c.query('UPDATE users SET games_played=games_played+1,wins=wins+$1,xp=xp+$2,streak=CASE WHEN $1=1 THEN streak+1 ELSE 0 END,best_streak=GREATEST(best_streak,CASE WHEN $1=1 THEN streak+1 ELSE 0 END) WHERE id=$3',[win?1:0,win?100:25,p.id]);await c.query("INSERT INTO user_achievements(user_id,achievement_id) SELECT id, 'first-win' FROM users WHERE id=$1 AND wins>=1 UNION SELECT id,'ten-wins' FROM users WHERE id=$1 AND wins>=10 UNION SELECT id,'hundred-games' FROM users WHERE id=$1 AND games_played>=100 UNION SELECT id,'five-streak' FROM users WHERE id=$1 AND best_streak>=5 ON CONFLICT DO NOTHING",[p.id]);}await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');console.error('Match persistence failed',e);}finally{c.release();}}
const botAt=new Map<string,number>();setInterval(()=>{for(const r of rooms.values()){const g=r.game;if(!g){if(Date.now()-r.lastActive>3600000)rooms.delete(r.code);continue;}if(g.status==='finished'){if(!r.saved){r.saved=true;void saveGame(r);}continue;}const p=g.players[g.turn];const key=g.id+':'+g.revision;const autonomous=p.bot||!p.connected;if(autonomous&&!botAt.has(key))botAt.set(key,Date.now()+1100+Math.random()*900);if((autonomous&&Date.now()>botAt.get(key)!)||(g.deadline&&Date.now()>g.deadline)){try{if(p.hand.length===2&&autonomous)act(g,p.id,{type:'uno'});act(g,p.id,autonomous?botAction(g):{type:g.drawn?'pass':'draw'});emitRoom(r);}catch{g.deadline=Date.now()+1000;}botAt.delete(key);}}if(botAt.size>1000)botAt.clear();},300);
app.get('/api/status',(_req,res)=>res.json({online:io.engine.clientsCount,rooms:rooms.size,database:!!db}));
if(process.env.NODE_ENV==='production'){app.use(express.static('dist'));app.get('*',(_req,res)=>res.sendFile('index.html',{root:'dist'}));}else{const {createServer}=await import('vite');const vite=await createServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);}
http.listen(Number(process.env.PORT)||3000,'0.0.0.0',()=>console.log('UNO Club → http://localhost:'+ (process.env.PORT||3000)));
