import {useCallback,useEffect,useRef,useState} from 'react';
import {Camera,CameraOff,Mic,MicOff,PhoneOff,ShieldCheck,Video} from 'lucide-react';
import {socket} from '../lib';

type RemoteStream={id:string;stream:MediaStream};
type CallState={active:boolean;joining:boolean;local:MediaStream|null;remotes:RemoteStream[];mic:boolean;camera:boolean;error:string;join:()=>Promise<void>;leave:()=>void;toggleMic:()=>void;toggleCamera:()=>void};
const iceServers:RTCIceServer[]=[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}];

export function useRoomCall(roomCode?:string,meId?:string):CallState{
  const [local,setLocal]=useState<MediaStream|null>(null);const [remotes,setRemotes]=useState<RemoteStream[]>([]);const [joining,setJoining]=useState(false);const [mic,setMic]=useState(true);const [camera,setCamera]=useState(true);const [error,setError]=useState('');
  const peers=useRef(new Map<string,RTCPeerConnection>());const media=useRef<MediaStream|null>(null);const pendingIce=useRef(new Map<string,RTCIceCandidateInit[]>());
  const removePeer=useCallback((id:string)=>{peers.current.get(id)?.close();peers.current.delete(id);pendingIce.current.delete(id);setRemotes(items=>items.filter(item=>item.id!==id));},[]);
  const createPeer=useCallback((id:string)=>{const old=peers.current.get(id);if(old)return old;const pc=new RTCPeerConnection({iceServers});peers.current.set(id,pc);media.current?.getTracks().forEach(track=>pc.addTrack(track,media.current!));pc.onicecandidate=event=>{if(event.candidate)socket.emit('rtc:signal',{target:id,data:{candidate:event.candidate.toJSON()}});};pc.ontrack=event=>{const stream=event.streams[0];setRemotes(items=>[...items.filter(item=>item.id!==id),{id,stream}]);};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState))removePeer(id);};return pc;},[removePeer]);
  const leave=useCallback(()=>{socket.emit('rtc:leave');for(const id of peers.current.keys())removePeer(id);media.current?.getTracks().forEach(track=>track.stop());media.current=null;setLocal(null);setJoining(false);setError('');},[removePeer]);
  const join=useCallback(async()=>{if(!roomCode||!meId||media.current)return;setJoining(true);setError('');try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:{width:{ideal:640},height:{ideal:360},facingMode:'user'}});media.current=stream;setLocal(stream);socket.emit('rtc:join',async(response:{peers?:string[];error?:string})=>{if(response?.error){setError(response.error);leave();return;}for(const id of response?.peers||[]){const pc=createPeer(id);await pc.setLocalDescription(await pc.createOffer());socket.emit('rtc:signal',{target:id,data:{description:pc.localDescription?.toJSON()}});}setJoining(false);});}catch(err){setJoining(false);setError(err instanceof DOMException&&err.name==='NotAllowedError'?'Camera or microphone permission was declined.':'Camera could not start on this device.');}},[roomCode,meId,createPeer,leave]);
  useEffect(()=>{const signal=async({from,data}:{from:string;data:{description?:RTCSessionDescriptionInit;candidate?:RTCIceCandidateInit}})=>{try{const pc=createPeer(from);if(data.description){await pc.setRemoteDescription(data.description);for(const candidate of pendingIce.current.get(from)||[])await pc.addIceCandidate(candidate);pendingIce.current.delete(from);if(data.description.type==='offer'){await pc.setLocalDescription(await pc.createAnswer());socket.emit('rtc:signal',{target:from,data:{description:pc.localDescription?.toJSON()}});}}else if(data.candidate){if(pc.remoteDescription)await pc.addIceCandidate(data.candidate);else pendingIce.current.set(from,[...(pendingIce.current.get(from)||[]),data.candidate]);}}catch{removePeer(from);}};const peerJoined=async({id}:{id:string})=>{try{const pc=createPeer(id);await pc.setLocalDescription(await pc.createOffer());socket.emit('rtc:signal',{target:id,data:{description:pc.localDescription?.toJSON()}});}catch{removePeer(id);}};const peerLeft=({id}:{id:string})=>removePeer(id);socket.on('rtc:signal',signal);socket.on('rtc:peer-joined',peerJoined);socket.on('rtc:peer-left',peerLeft);return()=>{socket.off('rtc:signal',signal);socket.off('rtc:peer-joined',peerJoined);socket.off('rtc:peer-left',peerLeft);};},[createPeer,removePeer]);
  useEffect(()=>()=>leave(),[roomCode,leave]);
  const toggleMic=()=>{const next=!mic;media.current?.getAudioTracks().forEach(track=>track.enabled=next);setMic(next);};const toggleCamera=()=>{const next=!camera;media.current?.getVideoTracks().forEach(track=>track.enabled=next);setCamera(next);};
  return {active:!!local,joining,local,remotes,mic,camera,error,join,leave,toggleMic,toggleCamera};
}

function VideoTile({stream,label,muted=false}:{stream:MediaStream;label:string;muted?:boolean}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{if(ref.current)ref.current.srcObject=stream;},[stream]);return <div className="video-tile"><video ref={ref} autoPlay playsInline muted={muted}/><span>{label}</span></div>}
export function RoomCall({call,members,meId}:{call:CallState;members:any[];meId?:string}){
  if(!call.active&&!call.error)return null;
  const name=(id:string)=>members.find(member=>member.id===id)?.name||'Friend';
  return <aside className="call-panel" aria-label="Live camera and voice chat"><div className="call-head"><div><strong><Video size={16}/> Live table talk</strong><small><ShieldCheck size={12}/> Peer-to-peer · nothing is recorded</small></div><span className="live-pill">LIVE</span></div>{call.error?<div className="call-error">{call.error}<button className="secondary-button" onClick={call.join}>Try again</button></div>:<div className="video-grid">{call.local&&<VideoTile stream={call.local} label="You" muted/>}{call.remotes.map(remote=><VideoTile key={remote.id} stream={remote.stream} label={name(remote.id)}/>)}</div>}<div className="call-controls"><button className={!call.mic?'off':''} onClick={call.toggleMic} aria-label={call.mic?'Mute microphone':'Unmute microphone'}>{call.mic?<Mic/>:<MicOff/>}</button><button className={!call.camera?'off':''} onClick={call.toggleCamera} aria-label={call.camera?'Turn camera off':'Turn camera on'}>{call.camera?<Camera/>:<CameraOff/>}</button><button className="hangup" onClick={call.leave} aria-label="Leave live talk"><PhoneOff/></button></div></aside>
}
